import type { UiLabels } from "../providers/labels";

export const testLabels: UiLabels = {
	locale: "en",
	cancel: "Cancel",
	saveChanges: "Save changes",
	clear: "Clear",
	search: "Search",
	noResults: "No results",
	loadMore: "Load more",
	notSet: "Not set",
	nSelected: (count) => `${count} selected`,
	textOperators: {
		eq: "Equals",
		neq: "Does not equal",
		contains: "Contains",
		not_contains: "Does not contain",
		starts_with: "Starts with",
		ends_with: "Ends with",
	},
	moreActions: "More actions",
	loadFailed: "Couldn't load this",
	retry: "Try again",
	noPermission:
		"You don't have permission to do this. Ask an admin of this operator if you need access.",
	pickADate: "Pick a date",
	pickATime: "Pick a time",
	hour: "Hour",
	minute: "Minute",
	showPassword: "Show password",
	hidePassword: "Hide password",
	translated: "Translated",
	notTranslated: "Not translated",
	translation: "Translation",
	translationFallbackHelp:
		"Leave a field empty to use the default-language text.",
	notFound: (resource) => `${resource} not found`,
	resourceNotFound: "It may have been removed, or you don't have access to it.",
	goBack: "Go back",
	filterColumn: (column) => `Filter by ${column}`,
	audience: "Audience",
	price: "Price",
	resourceCreated: (resource) => `${resource} created`,
	resourceUpdated: (resource) => `${resource} updated`,
	resourceDeleted: (resource) => `${resource} deleted`,
};
